# Generated by Django 6.0.4 on 2026-04-23 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beers", "0002_badge_checkin_quantity_alter_challenge_icon_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(
                fields=["badge_type"], name="beers_badge_badge_t_c56ada_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(
                fields=["threshold"], name="beers_badge_thresho_41e4d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(fields=["name"], name="beers_badge_name_ca2018_idx"),
        ),
        migrations.AddIndex(
            model_name="beer",
            index=models.Index(fields=["name"], name="beers_beer_name_d604aa_idx"),
        ),
        migrations.AddIndex(
            model_name="beer",
            index=models.Index(fields=["abv"], name="beers_beer_abv_5f8e47_idx"),
        ),
        migrations.AddIndex(
            model_name="beer",
            index=models.Index(fields=["style"], name="beers_beer_style_i_a1a211_idx"),
        ),
        migrations.AddIndex(
            model_name="beer",
            index=models.Index(
                fields=["brewery"], name="beers_beer_brewery_68614d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="beer",
            index=models.Index(fields=["key"], name="beers_beer_key_286887_idx"),
        ),
        migrations.AddIndex(
            model_name="beerstyle",
            index=models.Index(fields=["name"], name="beers_beers_name_da80f8_idx"),
        ),
        migrations.AddIndex(
            model_name="beerstyle",
            index=models.Index(fields=["family"], name="beers_beers_family_4d8b0c_idx"),
        ),
        migrations.AddIndex(
            model_name="brewery",
            index=models.Index(fields=["name"], name="beers_brewe_name_09b5e8_idx"),
        ),
        migrations.AddIndex(
            model_name="brewery",
            index=models.Index(
                fields=["country"], name="beers_brewe_country_f35864_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brewery",
            index=models.Index(fields=["city"], name="beers_brewe_city_deed8c_idx"),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["required_count"], name="beers_chall_require_502abe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["required_style"], name="beers_chall_require_68bc8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(fields=["user"], name="beers_check_user_id_a68706_idx"),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(fields=["beer"], name="beers_check_beer_id_d510f2_idx"),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["created_at"], name="beers_check_created_dd8194_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["follower"], name="beers_follo_followe_5abb69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["followed"], name="beers_follo_followe_fca991_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbadge",
            index=models.Index(fields=["user"], name="beers_userb_user_id_6d1f27_idx"),
        ),
        migrations.AddIndex(
            model_name="userbadge",
            index=models.Index(fields=["badge"], name="beers_userb_badge_i_266a75_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["user"], name="beers_userp_user_id_aebea6_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["favorite_style"], name="beers_userp_favorit_eed707_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("follower", "followed"), name="unique_follow_relationship"
            ),
        ),
        migrations.AddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(
                fields=("user", "badge"), name="unique_user_badge"
            ),
        ),
    ]
