# Generated by Django 4.2.1 on 2026-04-22 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beers", "0002_badge_checkin_quantity_alter_challenge_icon_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "breweries",
                    models.ManyToManyField(
                        blank=True, related_name="manufacturers", to="beers.brewery"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManufacturerMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Account Admin"),
                            ("supply_chain", "Supply Chain Manager"),
                            ("sales", "Sales & Marketing"),
                            ("executive", "Executive / C-Suite"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="analytics.manufacturer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manufacturer_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "manufacturer")},
            },
        ),
        migrations.CreateModel(
            name="DemandSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                (
                    "granularity",
                    models.CharField(
                        choices=[
                            ("day", "Daily"),
                            ("week", "Weekly"),
                            ("month", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("checkin_count", models.IntegerField(default=0)),
                ("quantity_total", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("avg_rating", models.FloatField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "brewery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beers.brewery",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beers.beerstyle",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["granularity", "period_start"],
                        name="analytics_d_granula_24e027_idx",
                    ),
                    models.Index(
                        fields=["granularity", "style", "period_start"],
                        name="analytics_d_granula_e67b45_idx",
                    ),
                    models.Index(
                        fields=["granularity", "country", "period_start"],
                        name="analytics_d_granula_68e597_idx",
                    ),
                    models.Index(
                        fields=["granularity", "brewery", "period_start"],
                        name="analytics_d_granula_f01ca8_idx",
                    ),
                ],
            },
        ),
    ]
