# Generated by Django 4.2.1 on 2026-04-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="manufacturermembership",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="manufacturermembership",
            constraint=models.UniqueConstraint(
                fields=("user", "manufacturer"), name="unique_manufacturer_membership"
            ),
        ),
    ]
